behaviors:
  Fly:
    trainer_type: ppo
    
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 8
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
        
    keep_checkpoints: 1000
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
  
environment_parameters:
  speed:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Fly
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5000
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Fly
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5000
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 3.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Fly
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5000
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 6.0
      - name: Lesson3
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 9.0
        
  rate:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Fly
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5000
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 0.0
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Fly
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5000
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -1.0
            max_value: 1.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Fly
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5000
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -2.0
            max_value: 2.0
      - name: Lesson3
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: -3.0
            max_value: 3.0